-- auth-service 기준 스키마.
--
-- 이 파일이 스키마의 단일 소스다. 전에는 Hibernate 가 엔티티에서 만들었고(ddl-auto), 그러면 스키마가
-- 코드의 부산물이라 리뷰되지 않고 배포 순서도 정할 수 없다. 이제 엔티티는 이 스키마와 맞는지
-- 확인만 한다(ddl-auto=validate).
--
-- 두 realm(ADMIN/PORTAL)이 한 저장소를 공유하되 행은 realm 으로 분리된다. 그 분리가 코드의
-- 규율로만 서 있으면 언젠가 샌다 — 아래 유니크와 외래키가 그것을 DB 수준에서 붙든다.

-- ============================================================================
-- identity — 신원과 자격증명
-- ============================================================================

-- 인증 신원. 자격증명(비밀번호/이메일/소셜)은 이 행을 가리킨다.
CREATE TABLE identity_principal
(
    principal_id          varchar(36) PRIMARY KEY,
    subject_id            varchar(64)  NOT NULL,
    subject_type          varchar(20)  NOT NULL,
    status                varchar(20)  NOT NULL,
    last_authenticated_at timestamptz,
    created_at            timestamp(6),
    updated_at            timestamp(6),

    CONSTRAINT ck_identity_principal_subject_type CHECK (subject_type IN ('EMPLOYEE', 'CUSTOMER')),
    CONSTRAINT ck_identity_principal_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),

    -- 주체는 (유형, 식별자)로 유일하다. subject_id 만으로는 유일하지 않다 — realm 마다 다른 체계에서
    -- 발급되기 때문이다(직원은 사번 성격의 값, 고객은 UUID).
    CONSTRAINT uk_identity_principal_subject_type_subject_id UNIQUE (subject_type, subject_id),

    -- 자격증명이 (principal_id, subject_type) 를 통째로 참조할 수 있게 하는 유니크다.
    -- principal_id 가 이미 PK 라 유일성 자체는 새로울 것이 없지만, 외래키는 유니크한 열 조합만
    -- 참조할 수 있다. 이것이 아래 fk_*_principal 들의 대상이 된다.
    CONSTRAINT uk_identity_principal_id_subject_type UNIQUE (principal_id, subject_type)
);

-- 비밀번호 자격증명.
CREATE TABLE identity_password_account
(
    password_account_id varchar(36) PRIMARY KEY,
    principal_id        varchar(36)  NOT NULL,
    subject_type        varchar(20)  NOT NULL,
    login_id            varchar(100) NOT NULL,
    password_hash       varchar(100) NOT NULL,
    failed_attempts     integer      NOT NULL DEFAULT 0,
    locked_until        timestamptz,
    created_at          timestamptz,

    CONSTRAINT ck_identity_password_account_subject_type CHECK (subject_type IN ('EMPLOYEE', 'CUSTOMER')),

    -- 아이디는 realm 안에서만 유일하다. 전역 유일로 두면 두 realm 이 아이디 네임스페이스를 공유하게 되고
    -- (직원이 "hong" 을 쓰면 고객은 못 쓴다), 조회를 유형으로 좁힐 수도 없다.
    CONSTRAINT uk_identity_password_account_subject_type_login_id UNIQUE (subject_type, login_id),

    -- 자격증명의 subject_type 은 Principal 것을 복사한 값이라 어긋날 수 있다. 복합 외래키로 묶어
    -- 어긋난 행을 DB 가 받아주지 않게 한다 — 그러지 않으면 고객 자격증명이 직원 신원에 매달릴 수 있다.
    CONSTRAINT fk_identity_password_account_principal
        FOREIGN KEY (principal_id, subject_type)
            REFERENCES identity_principal (principal_id, subject_type)
);

-- 이메일(OTP) 로그인 식별자.
CREATE TABLE identity_email_account
(
    email_account_id varchar(36) PRIMARY KEY,
    principal_id     varchar(36)  NOT NULL,
    subject_type     varchar(20)  NOT NULL,
    email            varchar(255) NOT NULL,
    created_at       timestamptz,

    CONSTRAINT ck_identity_email_account_subject_type CHECK (subject_type IN ('EMPLOYEE', 'CUSTOMER')),
    -- 같은 사람이 직원이면서 고객일 수 있다. 이메일은 유형 안에서만 유일하다.
    CONSTRAINT uk_identity_email_account_subject_type_email UNIQUE (subject_type, email),
    CONSTRAINT fk_identity_email_account_principal
        FOREIGN KEY (principal_id, subject_type)
            REFERENCES identity_principal (principal_id, subject_type)
);

-- 소셜 로그인 연결. 비밀(토큰/시크릿)은 담지 않는다 — 자격 검증은 provider 가 한다.
CREATE TABLE identity_social_account
(
    social_account_id varchar(36) PRIMARY KEY,
    principal_id      varchar(36)  NOT NULL,
    subject_type      varchar(20)  NOT NULL,
    provider          varchar(20)  NOT NULL,
    provider_uid      varchar(191) NOT NULL,
    created_at        timestamptz,

    CONSTRAINT ck_identity_social_account_subject_type CHECK (subject_type IN ('EMPLOYEE', 'CUSTOMER')),
    CONSTRAINT uk_identity_social_account_subject_type_provider_uid
        UNIQUE (subject_type, provider, provider_uid),
    CONSTRAINT fk_identity_social_account_principal
        FOREIGN KEY (principal_id, subject_type)
            REFERENCES identity_principal (principal_id, subject_type)
);

-- 이메일 OTP 챌린지. 신원에 매달지 않는다 — 발송 시점에는 아직 인증된 주체가 없다.
CREATE TABLE identity_email_otp
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(255) NOT NULL,
    code_hash     varchar(100) NOT NULL,
    expires_at    timestamptz  NOT NULL,
    used          boolean      NOT NULL DEFAULT false,
    attempt_count integer      NOT NULL DEFAULT 0,
    created_at    timestamptz  NOT NULL
);

-- 미사용 최신 챌린지 조회와 쿨다운 판정이 이메일로 최신 행을 찾는다.
CREATE INDEX ix_identity_email_otp_email_created_at ON identity_email_otp (email, created_at DESC);

-- 신원에서 자격증명을 되짚는 경로(토큰에 이메일을 실을 때).
CREATE INDEX ix_identity_email_account_principal_id ON identity_email_account (principal_id);
CREATE INDEX ix_identity_password_account_principal_id ON identity_password_account (principal_id);
CREATE INDEX ix_identity_social_account_principal_id ON identity_social_account (principal_id);

-- ============================================================================
-- authz — 역할·권한·URL 접근규칙
-- ============================================================================

CREATE TABLE authz_role
(
    role_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    realm       varchar(20)  NOT NULL,
    role_code   varchar(50)  NOT NULL,
    role_name   varchar(100) NOT NULL,
    description varchar(500),
    use_yn      varchar(1)   NOT NULL DEFAULT 'Y',
    created_at  timestamp(6),
    updated_at  timestamp(6),

    CONSTRAINT ck_authz_role_realm CHECK (realm IN ('ADMIN', 'PORTAL')),
    CONSTRAINT ck_authz_role_use_yn CHECK (use_yn IN ('Y', 'N')),
    -- 역할은 코드로 찾는다(GrantRoleUseCase). realm 안에서 유일해야 어느 것을 줄지 정해진다.
    CONSTRAINT uk_authz_role_realm_role_code UNIQUE (realm, role_code)
);

CREATE TABLE authz_permission
(
    permission_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    realm           varchar(20)  NOT NULL,
    permission_code varchar(100) NOT NULL,
    permission_name varchar(200) NOT NULL,
    category        varchar(50)  NOT NULL,
    description     varchar(500),
    use_yn          varchar(1)   NOT NULL DEFAULT 'Y',
    created_at      timestamp(6),
    updated_at      timestamp(6),

    CONSTRAINT ck_authz_permission_realm CHECK (realm IN ('ADMIN', 'PORTAL')),
    CONSTRAINT ck_authz_permission_use_yn CHECK (use_yn IN ('Y', 'N')),
    -- 권한 코드는 토큰의 authLs 에 그대로 실려 소비 서비스가 문자열로 대조한다. 같은 realm 에
    -- 같은 코드가 둘이면 어느 쪽 정책이 적용됐는지 알 수 없다.
    CONSTRAINT uk_authz_permission_realm_permission_code UNIQUE (realm, permission_code)
);

CREATE TABLE authz_role_permission
(
    role_id       bigint NOT NULL,
    permission_id bigint NOT NULL,

    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_authz_role_permission_role
        FOREIGN KEY (role_id) REFERENCES authz_role (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_authz_role_permission_permission
        FOREIGN KEY (permission_id) REFERENCES authz_permission (permission_id) ON DELETE CASCADE
);

-- 권한에서 역할을 거슬러 찾는 조회(권한 삭제 영향 확인 등).
CREATE INDEX ix_authz_role_permission_permission_id ON authz_role_permission (permission_id);

CREATE TABLE authz_url_access
(
    url_access_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    realm         varchar(20)  NOT NULL,
    url_pattern   varchar(300) NOT NULL,
    http_method   varchar(10)  NOT NULL DEFAULT 'ALL',
    description   varchar(500),
    use_yn        varchar(1)   NOT NULL DEFAULT 'Y',
    sort_order    integer      NOT NULL DEFAULT 0,
    created_at    timestamp(6),
    updated_at    timestamp(6),

    CONSTRAINT ck_authz_url_access_realm CHECK (realm IN ('ADMIN', 'PORTAL')),
    CONSTRAINT ck_authz_url_access_use_yn CHECK (use_yn IN ('Y', 'N'))
    -- (realm, url_pattern, http_method) 에 유니크를 걸지 않는다. 접근제어는 sort_order 순으로 훑어
    -- 먼저 맞는 규칙을 쓰므로, 같은 패턴에 여러 규칙을 두고 순서로 가르는 사용이 성립한다.
);

-- 규칙 캐시는 realm 단위로 통째로 읽고 sort_order 로 훑는다.
CREATE INDEX ix_authz_url_access_realm_sort_order ON authz_url_access (realm, sort_order);

CREATE TABLE authz_url_permission
(
    url_access_id bigint NOT NULL,
    permission_id bigint NOT NULL,

    PRIMARY KEY (url_access_id, permission_id),
    CONSTRAINT fk_authz_url_permission_url_access
        FOREIGN KEY (url_access_id) REFERENCES authz_url_access (url_access_id) ON DELETE CASCADE,
    CONSTRAINT fk_authz_url_permission_permission
        FOREIGN KEY (permission_id) REFERENCES authz_permission (permission_id) ON DELETE CASCADE
);

CREATE INDEX ix_authz_url_permission_permission_id ON authz_url_permission (permission_id);

-- 주체에게 부여된 역할. 주체는 identity 의 subject_id 를 가리키지만 외래키를 걸지 않는다 —
-- authz 는 identity 와 다른 서브도메인이고, 나중에 서비스가 갈라지면 같은 DB 에 있지 않을 수 있다.
CREATE TABLE authz_subject_role
(
    realm       varchar(20) NOT NULL,
    subject_id  varchar(64) NOT NULL,
    role_id     bigint      NOT NULL,
    assigned_at timestamp(6),

    PRIMARY KEY (realm, subject_id, role_id),
    CONSTRAINT ck_authz_subject_role_realm CHECK (realm IN ('ADMIN', 'PORTAL')),
    CONSTRAINT fk_authz_subject_role_role
        FOREIGN KEY (role_id) REFERENCES authz_role (role_id) ON DELETE CASCADE
);

-- 토큰 발급 때마다 (realm, subject_id) 로 권한을 모은다 — PK 앞부분이라 별도 인덱스는 필요없다.
-- 역할 삭제 영향 확인은 role_id 로 거슬러 찾는다.
CREATE INDEX ix_authz_subject_role_role_id ON authz_subject_role (role_id);

-- realm 전역 인가 정책의 리비전. 정책이 바뀌면 올라가고, 발급된 토큰에 실려 옛 토큰을 가려낸다.
CREATE TABLE authz_revision
(
    realm       varchar(20) PRIMARY KEY,
    revision_no bigint NOT NULL DEFAULT 1,
    updated_at  timestamp(6),

    CONSTRAINT ck_authz_revision_realm CHECK (realm IN ('ADMIN', 'PORTAL'))
);
